ROOST.AI Integration
launchdarkly/integration-framework pull request #24
Opened 2023-02-13 07:05 UTC by Divyeshzb

This PR introduces a new integration with [Roost](https://roost.ai), Ephemeral DevOps Platform.

**Requirements**

- [x] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [x] I have updated my user documentation

**Availability**
Roost.ai is partner to LaunchDarkly. 

Roost provide a third party integration of LaunchDarkly in UI in its EaaS view where user can manage LaunchDarkly Project , Environment and feature flag directly from Roost UI.

**Request preview**

`➜  integration-framework git:(main) ✗ npm run preview roost.ai

> @launchdarkly/integration-framework@1.0.0 preview /Users/divyesh/go/src/github.com/roost-io/integration-framework
> node preview.js "roost.ai"

The "roost.ai" integration does not make any outbound requests from LaunchDarkly.`

We already created a [confluence documentation](https://zbio.atlassian.net/wiki/spaces/RFD/pages/1748500481/Roost+LaunchDarkly+Integration) for the user to enable Launch Darkly Integration in Roost.

Let me know if any question.Thankyou

2023-02-17 00:23 UTC, Divyeshzb commented
Thankyou @InTheCloudDan for the changes request. Made the changes for same.

2023-03-03 15:15 UTC, InTheCloudDan requested changes
@Divyeshzb Can you accept these additional suggestions and I'll be able to get this merged in today, thanks!

2023-03-03 15:15 UTC, InTheCloudDan commented on integrations/roost.ai/manifest.json
> +    "square": "assets/images/square.svg",
```suggestion
    "square": "assets/square.svg",
```

2023-03-03 15:15 UTC, InTheCloudDan commented on integrations/roost.ai/manifest.json
> +    "horizontal": "assets/images/horizontal.svg"
```suggestion
    "horizontal": "assets/horizontal.svg"
```

2023-03-03 15:20 UTC, Divyeshzb commented
@InTheCloudDan Done the suggested changes. Thanks!!

2023-03-03 15:21 UTC, InTheCloudDan approved these changes

2023-03-03 15:24 UTC, InTheCloudDan commented
@Divyeshzb I thought the images were the only changes but EOF is failing. Can you add a newline at end of the manifest file? And can you also add in the manifest: `"otherCapabilities": ["external"]`

2023-03-03 15:33 UTC, Divyeshzb commented
@InTheCloudDan added the otherCapabilities key and also ran prettier:check script for the manifest.

2023-03-03 15:47 UTC, Divyeshzb commented
@InTheCloudDan I have resolved EOF error in roost.ai integration images. Now according to logs cloudquery integration have the issues.

2023-03-08 06:13 UTC, closed without merging