manifest for okteto integration
launchdarkly/integration-framework pull request #33
Opened 2023-04-16 19:23 UTC by rberrelleza

**Requirements**

- [x] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [x] I have updated my user documentation
- [x] I have updated my developer documentation (my integration README)
- [x] I have submitted the [Become a Partner](https://launchdarkly.com/partners/) form

**Intended availability**

If you're adding a new integration, let us know if you are a community member or a partner.

If you are a partner, your integration will be available to all customers.

If you're part of the community and submitting an integration for your own purposes or internal teams, specify your company name so that we can verify your identity and enable the integration for your account.

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

If you're adding a new integration, provide some context into how LaunchDarkly and the third-party service should interact.

If you're modifying an existing integration, provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

If you're modifying an existing integration, provide a clear and concise description of any alternative solutions or features you've considered.

**Provide a request preview**

Include the output from running `npm run preview <INTEGRATION_NAME>`.

**Additional context**

Add any other context about the pull request here.

2023-04-17 14:24 UTC, InTheCloudDan requested changes
If we can get this change and the `launchdarklyDocs` value updated we should be all set.

2023-04-17 14:24 UTC, InTheCloudDan commented on integrations/okteto/manifest.json
> +  "description": "The LaunchDarkly Okteto integration enables you to automatically create a LaunchDarkly environment every time your team creates a development or preview environment. With this, your
```suggestion
  "description": "Automatically create a LaunchDarkly environment every time your team creates a development or preview environment in Okteto. This integration ensures your new LaunchDarkly environment always has the most up-to-date flag targeting. Okteto will automatically manage the lifecycle of the LaunchDarkly environment for you.",
```

We don't currently have support for Markdown so suggesting some slightly different wording so it's easier to parse in the format.

2023-04-18 09:07 UTC, rberrelleza commented
> If we can get this change and the `launchdarklyDocs` value updated we should be all set.

all done @InTheCloudDan !

2023-04-18 10:34 UTC, InTheCloudDan approved these changes

2023-04-18 10:34 UTC, merged