adding ctrlstack integration manifest
launchdarkly/integration-framework pull request #36
Opened 2023-06-08 18:14 UTC by jj-ctrlstack

**Requirements**

- [x] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [x] I have updated my user documentation
- [ ] I have updated my developer documentation (my integration README)
- [x] I have submitted the [Become a Partner](https://launchdarkly.com/partners/) form

**Intended availability**

Partner: CtrlStack

**Related issues**

N/A

**Describe the solution you've provided**

CtrlStack is a change intelligence platform for better observability. With its ability to observe system changes and data relationships across the stack, CtrlStack provides DevOps teams contextual understanding of system issues for faster incident investigation. Add LaunchDarkly feature flag events to CtrlStack to know when an alert or change in data behavior is directly or indirectly caused by toggling of a feature flag.

**Describe alternatives you've considered**

N/A

**Provide a request preview**

N/A

**Additional context**

N/A

2023-06-14 20:47 UTC, InTheCloudDan requested changes
@jj-ctrlstack if we can get these 2 small changes done this looks to get merged, thanks!

2023-06-14 20:47 UTC, InTheCloudDan commented on integrations/ctrlstack/manifest.json
> +  "details": "CtrlStack is a change intelligence platform for better observability. With its ability to observe system changes and data relationships across the stack, CtrlStack provides DevOps teams
```suggestion
  "details": "CtrlStack is a change intelligence platform for better observability. With its ability to observe system changes and data relationships across the stack, CtrlStack provides DevOps teams contextual understanding of system issues for faster incident investigation.<br><br>Add LaunchDarkly feature flag events to CtrlStack to know when an alert or change in data behavior is directly or indirectly caused by toggling of a feature flag.",
```

2023-06-14 20:47 UTC, InTheCloudDan commented on integrations/ctrlstack/manifest.json
> +  "categories": ["monitoring", "developer-tools", "automation"],
```suggestion
  "categories": ["monitoring", "developer-tools"],
```

2023-06-14 21:47 UTC, jj-ctrlstack commented
@InTheCloudDan done! Thanks

2023-06-15 12:38 UTC, InTheCloudDan approved these changes

2023-06-15 12:38 UTC, merged