Add Snowplow LaunchDarkly integration
launchdarkly/integration-framework pull request #37
Opened 2023-06-23 18:10 UTC by adatzer

**Requirements**

- [x] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [x] I have updated my user documentation
- [x] I have updated my developer documentation (my integration README)
- [x] I have submitted the [Become a Partner](https://launchdarkly.com/partners/) form

**Intended availability**

Partner

**Related issues**

Not applicable

**Describe the solution you've provided**

- [Documentation](https://docs.snowplow.io/docs/destinations/forwarding-events/google-tag-manager-server-side/launchdarkly-tag-for-gtm-ss/)
- [Repository](https://github.com/snowplow/snowplow-gtm-server-side-launchdarkly-tag)

**Describe alternatives you've considered**

Not applicable

**Provide a request preview**

```
> @launchdarkly/integration-framework@1.0.0 preview
> node preview.js "snowplow"

The "snowplow" integration does not make any outbound requests from LaunchDarkly.
```

**Additional context**

Nothing to add.

cc @igneel64 @jethron

2023-06-27 12:43 UTC, InTheCloudDan requested changes
A couple of small requests, looks great overall!

2023-06-27 12:43 UTC, InTheCloudDan commented on integrations/snowplow/manifest.json
> +  "description": "Use Snowplow with LaunchDarkly's Experimentation feature to forward the behavioral data you wish to use as metrics in your experiments.",
```suggestion
  "description": "Use Snowplow to forward the behavioral data as metrics in your LaunchDarkly experiments.",
```

2023-06-27 12:43 UTC, InTheCloudDan commented on integrations/snowplow/manifest.json
> +    "square": "assets/images/square.svg",
@adatzer is there any way we can use just the design icon part of your logo for this SVG? When it loads up it renders the long very small. You can see the difference of your logo compared to Splunk's. 
![CleanShot 2023-06-27 at 08 42 49](https://github.com/launchdarkly/integration-framework/assets/10308834/32bed39c-07c8-47f3-a6ea-acd028725bb0)

2023-06-28 15:39 UTC, adatzer commented
@InTheCloudDan thank you for reviewing! Just added a commit with the changes you suggested.

2023-06-28 23:07 UTC, InTheCloudDan approved these changes

2023-06-28 23:09 UTC, merged