Census manifest.json to use synchedSegment capability
launchdarkly/integration-framework pull request #55
Opened 2023-09-25 15:56 UTC by oneearedrabbit

**Requirements**

- [x] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [ ] I have updated my user documentation
- [ ] I have updated my developer documentation (my integration README)
- [ ] I have submitted the [Become a Partner](https://launchdarkly.com/partners/) form

**Intended availability**

Census is a partner.

**Related issues**

N/A

**Describe the solution you've provided**

Add synced segments capability to Census. Census is a data activation platform that help users to sync data from a warehouse to LaunchDarkly and other destinations.

**Describe alternatives you've considered**

N/A

**Provide a request preview**

```
> npm run preview census

> @launchdarkly/integration-framework@1.0.0 preview
> node preview.js census

The "census" integration does not make any outbound requests from LaunchDarkly.
```

**Additional context**

N/A

2023-09-25 20:18 UTC, InTheCloudDan requested changes
@oneearedrabbit sorry for the confusion here. Can you create a 2nd directory that's separate from this one? A lot of the manifest data can stay the same but we want it to show up as 2 different integrations we can provide the proper information for end users. You can see for example how we have 2 Segment.io integrations. Happy to hop on a call to discuss this.

2023-09-25 20:20 UTC, oneearedrabbit commented
@InTheCloudDan Yes, totally! Do you want me to rename the original integration to "census-integration1" or modify only the synced segments one to "census-integration2"?

2023-09-25 21:15 UTC, oneearedrabbit commented
Validated new "census-synced-segments" integration locally:
```
> npm run start:server

> @launchdarkly/integration-framework@1.0.0 start:server
> npm run build:server && node dist/server/src/index.js


> @launchdarkly/integration-framework@1.0.0 build:server
> rimraf ./dist && tsc

Validation app listening on port 3001

[synced-segment]:  Processing ptr: '/environment_id' for manifest field: 'environmentIdPath'
[synced-segment]:  Processing ptr: '/context_kind' for manifest field: 'contextKindPath'
[synced-segment]:  Processing ptr: '/batch/0/cohort_id' for manifest field: 'cohordIdPath'
[synced-segment]:  Processing ptr: '/batch/0/cohort_name' for manifest field: 'cohortNamePath'
[synced-segment]:  Processing ptr: '/batch' for manifest field: 'memberArrayPath'
[synced-segment]:  Processing ptr: '/value' for manifest field: 'booleanMembershipPath'
[synced-segment]:  Processing ptr: '/user_id' for manifest field: 'memberIdPath'
[synced-segment]:  Processing ptr: '/cohort_id' for manifest field: 'cohortIdPath'
[synced-segment]:  Processing ptr: '/cohort_name' for manifest field: 'cohortNamePath'
[synced-segment]:  
New Segment Key: census-synced-segments-users
[synced-segment]:  Request Parser Result: {
  "environmentId": "production",
  "contextKind": "user",
  "batch": [
    {
      "userId": "1",
      "cohortId": "users",
      "cohortName": "users",
      "value": true
    }
  ]
}
```

2023-09-27 17:29 UTC, InTheCloudDan approved these changes

2023-09-27 17:29 UTC, merged