sumatra-synced-segments integration
launchdarkly/integration-framework pull request #64
Opened 2024-01-29 23:00 UTC by GregKuhlmann

**Requirements**

- [x] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [x] I have updated my user documentation
- [x] I have updated my developer documentation (my integration README)
- [x] I have submitted the [Become a Partner](https://launchdarkly.com/partners/) form

**Intended availability**

If you're adding a new integration, let us know if you are a community member or a partner.

partner.

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

If you're adding a new integration, provide some context into how LaunchDarkly and the third-party service should interact.

# Syncing segments from Sumatra Audiences

Sumatra is a conversion optimization platform that identifies key
customer segments from online behavior and delivers those audiences
to create targeted experiments and personalized experiences.
You can use this integration to leverage Sumatra audiences in LaunchDarkly.

**Describe alternatives you've considered**

If you're modifying an existing integration, provide a clear and concise description of any alternative solutions or features you've considered.

**Provide a request preview**

Include the output from running `npm run preview <INTEGRATION_NAME>`.

**Additional context**

Add any other context about the pull request here.

2024-02-02 16:28 UTC, InTheCloudDan commented
@GregKuhlmann this looks good, can you run `npm run prettier:write` and commit the changes. That should fix the build failure and I can get this merged after.

2024-02-02 16:29 UTC, InTheCloudDan requested changes
Run `npm run prettier:write` to fix build failures.

2024-02-02 17:30 UTC, GregKuhlmann commented
@InTheCloudDan Pushed `prettier` changes.

2024-02-06 15:32 UTC, InTheCloudDan approved these changes

2024-02-06 15:32 UTC, merged