Add Port integration
launchdarkly/integration-framework pull request #70
Opened 2024-05-02 11:21 UTC by MPTG94

**Requirements**

- [X] I have followed the repository's [pull request submission guidelines](../blob/main/README.md#submitting-pull-requests)
- [X] I have updated my user documentation
- [X] I have updated my developer documentation (my integration README)
- [X] I have submitted the [Become a Partner](https://launchdarkly.com/partners/) form

**Intended availability**

> If you're adding a new integration, let us know if you are a community member or a partner.
> 
> If you are a partner, your integration will be available to all customers.
> 
> If you're part of the community and submitting an integration for your own purposes or internal teams, specify your company name so that we can verify your identity and enable the integration for your account.

Partner

**Related issues**

> Provide links to any issues in this repository or elsewhere relating to this pull request.

N/A

**Describe the solution you've provided**

> If you're adding a new integration, provide some context into how LaunchDarkly and the third-party service should interact.
> 
> If you're modifying an existing integration, provide a clear and concise description of what you expect to happen.
> 

Port's LaunchDarkly integration allows you to import projects, flags and environments from your LaunchDarkly account into Port, according to your mapping and definition.

**Describe alternatives you've considered**

> If you're modifying an existing integration, provide a clear and concise description of any alternative solutions or features you've considered.

N/A

**Provide a request preview**

> Include the output from running `npm run preview <INTEGRATION_NAME>`.

The Port integration does not make any outbound requests from LaunchDarkly.

**Additional context**

Add any other context about the pull request here.

2024-05-07 17:44 UTC, InTheCloudDan requested changes

2024-05-07 17:44 UTC, InTheCloudDan commented on integrations/port/manifest.json
> +  "overview": "Import projects, flags and environments from you LaunchDarkly account into Port.",
```suggestion
  "overview": "Access Feature Flags, Projects and Environments from your LaunchDarkly account in Port.",
```

2024-05-07 17:44 UTC, InTheCloudDan commented on integrations/port/manifest.json
> +  "description": "Port's LaunchDarkly integration allows you to import projects, flags and environments from your LaunchDarkly account into Port, according to your mapping and definition.",
```suggestion
  "description": "Port's LaunchDarkly integration allows you to access Feature Flags, Projects and Environments from your LaunchDarkly account in Port, according to your mapping and definition.",
```

2024-05-08 11:04 UTC, MPTG94 commented
Hey @InTheCloudDan, everything is fixed 👍

2024-05-09 19:05 UTC, InTheCloudDan approved these changes

2024-05-09 19:05 UTC, merged