convex: replace auth header with hmac signature
launchdarkly/integration-framework pull request #80
Opened 2024-09-06 19:23 UTC by atrakh

I'm replacing the `Authorization:  Bearer` header with an HMAC signature, using the same form variable as the shared secret. Updating some of the descriptions and placeholders as well

2024-09-10 13:58 UTC, ldhenry requested changes
I just looked into it and unfortunately, our featureStore integrations do not support using HMAC signatures today. Would you be OK with keeping it as a token or is that a hard requirement?

2024-09-10 18:03 UTC, atrakh commented
We can keep it as a token, I'll update this PR to only have the documentation changes

2024-09-11 07:09 UTC, ldhenry approved these changes

2024-09-13 13:31 UTC, InTheCloudDan approved these changes

2024-09-13 13:31 UTC, merged